baseURL = 'https://reels.my.id/'
languageCode = 'en-US'
defaultContentLanguage = 'en-us'
title = 'Segala Informasi Tips, Trik, dan Fakta Menarik di Reels.my.id' # Title on Meta Tags
paginate = 20
theme = 'ctheme'
enableRobotsTXT = true
disableKinds = ['section', 'posts']
disableHugoGeneratorInject = true

[permalinks]
  posts = '/:title/'
  pages = '/:title/'


[taxonomies]
  category = 'categories'

[outputs]
  page = ['HTML']
  home = ['HTML','RSS']
  section = ['HTML']
  taxonomyTerm = ['HTML']
  taxonomy = ['HTML']

[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss'
    baseName = 'rss'    

[params]
  title = 'reels.my.id' # Title on Header
  tagline = 'Segala Informasi Tips, Trik, dan Fakta Menarik'
  description = 'Reels.my.id adalah sumber terpercaya yang menyajikan beragam tips, trik, dan informasi umum terkini. Jelajahi blog kami dan temukan panduan praktis yang akan memperkaya pengetahuan Anda.'
  recentposts = 10 
  author = "Reels Creator"

[menu]



  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1

  [[menu.main]]
    identifier = 'categories'
    name = 'Categories'
    url = '/categories/'
    weight = 2

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 3

  [[menu.main]]
    identifier = 'privacy-policy'
    name = 'Privacy Policy'
    url = '/privacy-policy/'
    weight = 4

  [[menu.main]]
    identifier = 'dmca'
    name = 'DMCA'
    url = '/dmca/'
    weight = 5
